# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'FinTrack' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Firebase
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseMessaging'
  
  # UI e Charts
  pod 'Charts'
  
  # Networking
  pod 'Alamofire'
  
  # Utilitários
  pod 'SwiftKeychainWrapper'

end
